env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
steps:
  - group: ":test_tube: Tests"
    key: "tests"
    steps:
      - label: ":golangci-lint: lint :lint-roller:"
        key: "lint"
        cancel_on_build_failing: true
        plugins:
          - docker#v5.11.0:
              image: "registry.hub.docker.com/golangci/golangci-lint:latest-alpine"
              command: ["golangci-lint", "run", "-v"]
              always-pull: true
              environment:
                - "GOTOOLCHAIN=auto"
