env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
steps:
  - group: ":test_tube: Tests"
    key: "tests"
    steps:
      - label: ":golangci-lint: lint :lint-roller:"
        key: "lint"
        cancel_on_build_failing: true
        plugins:
          - docker#v5.11.0:
              image: "ghcr.io/theopenlane/build-image:latest"
              always-pull: true
              command: ["task", "go:lint"]
              environment:
                - "GOTOOLCHAIN=auto"
